version: "3"

services:
  db:
    image: mysql
    restart: always
    links:
      - adminer
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_USER: rajat
      MYSQL_PASSWORD: rajat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emp1
    ports:
      - 3302:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - data:/var/lib/mysql


  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

  app:
    build: ./App
    container_name: app_con
    image: app
    links:
      - db
      - api
    environment:
      ROOT_USER: 'rajat'
      ROOT_PASSWORD: 'rajat'
      HOST: db
      DB_NAME: 'emp1'
      API: host.docker.internal:81
    expose:
      - 4000


  api:
    build: ./Api
    container_name: api_con
    image: api
    links:
      - db
#      - nginx
    environment:
      ROOT_USER: 'rajat'
      ROOT_PASSWORD: 'rajat'
      HOST: db
      DB_NAME: 'emp1'
    expose:
      - 8000

  nginx:
    build: ./nginx
    restart: always
    container_name: nignx
    ports:
      - 80:80
      - 81:81
volumes:
  data:
    driver: local